### ISSUE TITLE
Pass experimental flag for better stack tracing

### ISSUE THREAD

**Issue by bradtaniguchi** [freeCodeCamp/CamperChan-discord#75]
**Is your feature request related to a problem? Please describe.**
When we get a discordjs error related to permissions we get limited stack traces:
```
DiscordAPIError: Missing Access
    at RequestHandler.execute (/home/brad/Projects/discord-bot-test/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'post',
  path: '/channels/723369420612829254/messages',
  code: 50001,
  httpStatus: 403
}
```

**Describe the solution you'd like**
Apparently there is a nodejs flag that we can pass to `node` (and thru `nodemon`) to get better tracing:
https://v8.dev/blog/v8-release-72#async-stack-traces

**Additional context**
This **might** or **might not** work, just gotta play around with it. Also passing it to nodemon might require us to change how nodemon is setup so we can pass flags directly to node more easily.

**Comment by bradtaniguchi** [comment]
This actually looks to be fixed with:
`https://github.com/discordjs/discord.js/pull/2744` (not a link to prevent links from that issue to this one hehe)

I don't see this fix locally with out errors, but it should have been fixed since 2018 0.o
